export const PRODUCTS_REQUEST="PRODUCTS_REQUEST";
export const PRODUCTS_FAILURE="PRODUCTS_FAILURE";

//GET
export const GET_MEN_PRODUCTS_SUCCESS="GET_MEN_PRODUCTS_SUCCESS";
export const GET_WOMEN_PRODUCTS_SUCCESS="GET_WOMEN_PRODUCTS_SUCCESS";

export const GET_SINGLE_PRODUCT_SUCCESS="GRT_SINGLE_PRODUCT_SUCCESS";
