export const PRODUCTS_REQUEST="PRODUCTS_REQUEST";
export const PRODUCTS_FAILURE="PRODUCTS_FAILURE";

//GET
export const GET_MEN_PRODUCTS_SUCCESS="GET_MEN_PRODUCTS_SUCCESS";
export const GET_WOMEN_PRODUCTS_SUCCESS="GET_WOMEN_PRODUCTS_SUCCESS";

//Pagination
export const HANDLE_PAGE_CHANGE="HANDLE_PAGE_CHANGE";

export const GET_SINGLE_PRODUCT_SUCCESS="GRT_SINGLE_PRODUCT_SUCCESS";

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const GET_FROM_CART_SUCCESS = 'GET_FROM_CART_SUCCESS'

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'