
export const ADD_TO_CART_PROCESS="ADD_TO_CART_PROCESS";
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL="ADD_TO_CART_FAIL";


export const GET_CART_PROCESS="GET_CART_PROCESS";
export const GET_CART_SUCCESS="GET_CART_SUCCESS";
export const GET_CART_FAIL="GET_CART_FAIL";


export const DELETE_FROM_CART_PROCESS="DELETE_FROM_CART_PROCESS";
export const DELETE_FROM_CART_SUCCESS="DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_FAIL="DELETE_FROM_CART_FAIL";





export const EDIT_CART_ITEM_PROCESS="EDIT_CART_ITEM_PROCESS";
export const EDIT_CART_ITEM_SUCCESS="EDIT_CART_ITEM_SUCCESS";
export const EDIT_CART_ITEM_FAIL="EDIT_CART_ITEM_FAIL";

